import { spawnSync } from 'node:child_process';
import { mkdir, mkdtemp, readdir, readFile, realpath, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { runCli, type CliTelemetryHooks } from '../src/cli.js';
import { runCommand } from '../src/commands.js';
import { captureTreeState } from '../src/init-filesystem.js';
import { CaptureStream, ReadyInitRunner } from './helpers.js';

// Runtime evidence for task 2.6: for the commands covered here, Liftoff neither loads nor executes
// repository-supplied plugin-looking files, package shadows, plugin-looking configuration or
// plugin-path environment settings. Every sentinel is generated by this file; it writes a marker,
// sets a global flag and throws when executed. Negative controls run the same sentinel programs,
// plus generated loader probes, in joined child processes to prove the detection works. Loader
// probes resolve bare package specifiers first and load only the exact owned sentinel file, so an
// unexpected package elsewhere on the host is never executed. Liftoff
// commands run in-process against current source with a fake command runner, no-op telemetry and
// no release lookups. This is behavior evidence for the covered commands only. It is not a sandbox
// or network boundary, and it makes no claim about external toolchains, dependency internals or
// Node startup options (NODE_OPTIONS, NODE_PATH, --import/--require).

const sentinelFlag = Symbol.for('liftoff.test.pluginSentinel');
/** Distinctive fragments of every sentinel location; none may appear in a runner command, argument or cwd. */
const sentinelTokens = ['evil', 'liftoff.config.m', 'liftoff.config.js', 'liftoff.plugins', 'poisoned-sentinel'];
const poisonedManifest = `${JSON.stringify({
  name: 'poisoned-sentinel',
  version: '0.0.0',
  scripts: { postinstall: 'node ../../.liftoff/plugins/evil.mjs' }
}, null, 2)}\n`;
const projectFlags = [
  '--type', 'standard', '--api', 'node', '--cloud', 'azure', '--region', 'eastus', '--environments', 'prod',
  '--no-frontend', '--spec', 'spec-kit', '--agents', 'copilot', '--yes'
];

interface PlantedSentinel {
  readonly id: string;
  readonly relative: string;
}

interface SentinelLayout {
  readonly root: string;
  readonly markers: string;
  /** Generated files that execute a sentinel when run directly with Node. */
  readonly executables: readonly PlantedSentinel[];
  readonly files: readonly string[];
}

const roots: string[] = [];

afterEach(async () => {
  vi.unstubAllEnvs();
  Reflect.deleteProperty(globalThis, sentinelFlag);
  for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true });
});

async function ownedRoot(): Promise<string> {
  const root = await mkdtemp(path.join(os.tmpdir(), 'lpx-'));
  roots.push(root);
  return root;
}

function sentinelProgram(format: 'cjs' | 'esm' | 'ts', id: string, marker: string): string {
  const effect = [
    `writeFileSync(${JSON.stringify(marker)}, ${JSON.stringify(`${id}\n`)});`,
    `globalThis[Symbol.for('liftoff.test.pluginSentinel')] = ${JSON.stringify(id)};`,
    `throw new Error(${JSON.stringify(`plugin sentinel ${id} executed`)});`
  ];
  if (format === 'cjs') return [`const { writeFileSync } = require('node:fs');`, ...effect, ''].join('\n');
  const typed = format === 'ts' ? [`const sentinelId: string = ${JSON.stringify(id)};`, 'void sentinelId;'] : [];
  return [`import { writeFileSync } from 'node:fs';`, ...typed, ...effect, ''].join('\n');
}

function packageManifest(name: string, esm: boolean): string {
  return `${JSON.stringify({ name, version: '0.0.0', ...(esm ? { type: 'module', exports: './index.js' } : { main: 'index.js' }) })}\n`;
}

async function plantSentinels(root: string, markers: string): Promise<SentinelLayout> {
  await mkdir(markers, { recursive: true });
  const marker = (id: string): string => path.join(markers, `${id}.executed`);
  const files: [string, string][] = [
    ['.liftoff/plugins/evil.mjs', sentinelProgram('esm', 'liftoff-mjs', marker('liftoff-mjs'))],
    ['.liftoff/plugins/evil.cjs', sentinelProgram('cjs', 'liftoff-cjs', marker('liftoff-cjs'))],
    ['.liftoff/plugins/evil.ts', sentinelProgram('ts', 'liftoff-ts', marker('liftoff-ts'))],
    ['plugins/evil/package.json', '{ "type": "module" }\n'],
    ['plugins/evil/index.js', sentinelProgram('esm', 'plugins-js', marker('plugins-js'))],
    ['node_modules/liftoff-plugin-evil/package.json', packageManifest('liftoff-plugin-evil', true)],
    ['node_modules/liftoff-plugin-evil/index.js', sentinelProgram('esm', 'package-esm', marker('package-esm'))],
    ['node_modules/liftoff-plugin-evil-cjs/package.json', packageManifest('liftoff-plugin-evil-cjs', false)],
    ['node_modules/liftoff-plugin-evil-cjs/index.js', sentinelProgram('cjs', 'package-cjs', marker('package-cjs'))],
    ['node_modules/@inquirer/prompts/package.json', packageManifest('@inquirer/prompts', true)],
    ['node_modules/@inquirer/prompts/index.js', sentinelProgram('esm', 'inquirer-shadow', marker('inquirer-shadow'))],
    ['liftoff.config.mjs', sentinelProgram('esm', 'config-mjs', marker('config-mjs'))],
    ['liftoff.config.js', sentinelProgram('cjs', 'config-js', marker('config-js'))],
    ['liftoff.plugins.json', `${JSON.stringify({
      plugins: ['./plugins/evil/index.js', './.liftoff/plugins/evil.mjs', 'liftoff-plugin-evil']
    }, null, 2)}\n`],
    ['assets/locks/node-backend/package.json', poisonedManifest],
    ['assets/plugins/node-fastify/node-backend/package.json', poisonedManifest]
  ];
  for (const [relative, content] of files) {
    const file = path.join(root, ...relative.split('/'));
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content);
  }
  return {
    root,
    markers,
    files: files.map(([relative]) => relative).sort(),
    executables: [
      { id: 'liftoff-mjs', relative: '.liftoff/plugins/evil.mjs' },
      { id: 'liftoff-cjs', relative: '.liftoff/plugins/evil.cjs' },
      { id: 'liftoff-ts', relative: '.liftoff/plugins/evil.ts' },
      { id: 'plugins-js', relative: 'plugins/evil/index.js' },
      { id: 'config-mjs', relative: 'liftoff.config.mjs' },
      { id: 'config-js', relative: 'liftoff.config.js' }
    ]
  };
}

async function executedSentinels(markers: string): Promise<string[]> {
  return (await readdir(markers)).sort();
}

function sentinelFlagValue(): unknown {
  return Reflect.get(globalThis, sentinelFlag);
}

function sentinelReferences(value: unknown): string[] {
  const text = JSON.stringify(value);
  return sentinelTokens.filter((token) => text.includes(token));
}

/**
 * What Liftoff asked the runner to execute: executable, arguments and working directory. Inherited
 * environment values are passed through to external commands by design and are reported separately.
 */
function runnerCommands(runner: ReadyInitRunner): { executable: string; args: string[]; cwd?: string }[] {
  return runner.callDetails.map(({ command, options }) => ({
    executable: command.executable,
    args: [...command.args],
    ...(options?.cwd === undefined ? {} : { cwd: options.cwd })
  }));
}

/** Read-only git root discovery that initialization performs before validating a plan. */
const gitRootDiscovery = { executable: 'git', args: ['rev-parse', '--show-toplevel'] };

/** Minimal environment for joined negative-control processes: no NODE_OPTIONS or inherited settings. */
function controlEnvironment(root: string, extra: NodeJS.ProcessEnv = {}): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { PATH: process.env.PATH ?? '', HOME: root, USERPROFILE: root, TMPDIR: root, TMP: root, TEMP: root, ...extra };
  for (const key of ['SystemRoot', 'SYSTEMROOT', 'ComSpec', 'COMSPEC', 'PATHEXT']) {
    if (process.env[key] !== undefined) env[key] = process.env[key];
  }
  return env;
}

interface ControlRun {
  readonly file: string;
  readonly status: number | null;
  readonly signal: string | null;
  readonly error?: string;
  readonly stderr: string;
}

function runGeneratedFile(file: string, cwd: string, env: NodeJS.ProcessEnv): ControlRun {
  const result = spawnSync(process.execPath, [file], { cwd, env, encoding: 'utf8', timeout: 20_000, killSignal: 'SIGKILL' });
  return {
    file: path.relative(cwd, file).split(path.sep).join('/'),
    status: result.status,
    signal: result.signal,
    ...(result.error === undefined ? {} : { error: result.error.message }),
    stderr: result.stderr.slice(0, 400)
  };
}

/**
 * A generated loader for a bare package specifier. It resolves without loading, records the
 * canonical resolution, and loads only when that is the exact owned sentinel file. Any other
 * resolution (for example, a package in an ancestor node_modules on a shared host) exits with
 * status 3 before anything is loaded.
 */
function guardedLoader(format: 'cjs' | 'esm', specifier: string, expectedFile: string, resultFile: string): string {
  const setup = format === 'esm'
    ? [
      "import { realpathSync, writeFileSync } from 'node:fs';",
      "import { fileURLToPath, pathToFileURL } from 'node:url';",
      `const resolveSpecifier = () => fileURLToPath(import.meta.resolve(${JSON.stringify(specifier)}));`
    ]
    : [
      "const { realpathSync, writeFileSync } = require('node:fs');",
      `const resolveSpecifier = () => require.resolve(${JSON.stringify(specifier)});`
    ];
  return [
    ...setup,
    `const record = (value) => writeFileSync(${JSON.stringify(resultFile)}, JSON.stringify(value));`,
    'let resolved;',
    'try { resolved = realpathSync(resolveSpecifier()); } catch (error) { record({ resolved: null, code: error?.code ?? String(error) }); process.exit(4); }',
    `const expected = realpathSync(${JSON.stringify(expectedFile)});`,
    'record({ resolved, expected, match: resolved === expected });',
    'if (resolved !== expected) process.exit(3);',
    format === 'esm' ? 'await import(pathToFileURL(resolved).href);' : 'require(resolved);',
    ''
  ].join('\n');
}

/** A generated ESM program that only resolves a specifier; an unexpected resolution exits 3 without loading. */
function resolutionOnlyProbe(specifier: string, resultFile: string): string {
  return [
    "import { realpathSync, writeFileSync } from 'node:fs';",
    "import { fileURLToPath } from 'node:url';",
    `const record = (value) => writeFileSync(${JSON.stringify(resultFile)}, JSON.stringify(value));`,
    'let resolved;',
    `try { resolved = realpathSync(fileURLToPath(import.meta.resolve(${JSON.stringify(specifier)}))); }`,
    'catch (error) { record({ resolved: null, code: error?.code ?? String(error) }); process.exit(0); }',
    'record({ resolved });',
    'process.exit(3);',
    ''
  ].join('\n');
}

interface ResolutionRecord {
  readonly resolved: string | null;
  readonly expected?: string;
  readonly match?: boolean;
  readonly code?: string;
}

async function resolutionRecord(file: string): Promise<ResolutionRecord> {
  return JSON.parse(await readFile(file, 'utf8')) as ResolutionRecord;
}

interface Invocation {
  readonly argv: readonly string[];
  readonly code: number;
  readonly out: string;
  readonly err: string;
  readonly runner: ReadyInitRunner;
}

const noTelemetry: CliTelemetryHooks = {
  beforeCommand: async () => false,
  afterCommand: async () => undefined
};

async function invoke(
  argv: readonly string[],
  cwd: string,
  options: { runner?: ReadyInitRunner; env?: NodeJS.ProcessEnv; previewHome?: string } = {}
): Promise<Invocation> {
  const stdout = new CaptureStream();
  const stderr = new CaptureStream();
  const runner = options.runner ?? new ReadyInitRunner();
  const previewHome = options.previewHome ?? path.join(path.dirname(cwd), 'preview-home');
  const code = await runCli({
    argv: [...argv],
    cwd,
    stdout,
    stderr,
    telemetry: noTelemetry,
    env: { CI: 'true', DO_NOT_TRACK: '1', LIFTOFF_TELEMETRY: '0', ...options.env },
    execute: (parsed, context) => runCommand(parsed, {
      ...context,
      runner,
      updatePreview: { homedir: previewHome, env: {} },
      stableReleaseLookup: async () => {
        throw new Error('plugin isolation tests never query release metadata');
      }
    })
  });
  return { argv, code, out: stdout.text(), err: stderr.text(), runner };
}

function normalizedOutput(invocation: Invocation, ...paths: string[]): string {
  let text = `${invocation.code}\n${invocation.out}\n${invocation.err}`;
  for (const value of paths) text = text.split(value).join('<root>');
  return text;
}

/** projectFlags with values replaced, flags removed (null) or appended. */
function projectArgs(replacements: Readonly<Record<string, string | null>> = {}): string[] {
  const args: string[] = [];
  for (let index = 0; index < projectFlags.length; index += 1) {
    const flag = projectFlags[index] ?? '';
    const next = projectFlags[index + 1];
    const takesValue = next !== undefined && !next.startsWith('--');
    if (takesValue) index += 1;
    const replacement = replacements[flag];
    if (replacement === null) continue;
    args.push(flag);
    if (takesValue) args.push(replacement ?? next);
  }
  for (const [flag, value] of Object.entries(replacements)) {
    if (value !== null && !projectFlags.includes(flag)) args.push(flag, value);
  }
  return args;
}

function recordEvidence(meta: object, evidence: Record<string, unknown>): void {
  Object.assign(meta, { pluginExecutionEvidence: evidence });
}

describe('repository-supplied plugin content (2.6)', () => {
  it('detects every generated sentinel when executed, loading packages only after verified resolution (negative control)', async ({ task }) => {
    const root = await ownedRoot();
    const layout = await plantSentinels(path.join(root, 'control'), path.join(root, 'markers'));
    const resolutions = path.join(root, 'resolutions');
    await mkdir(resolutions);
    const packageFile = (...parts: string[]): string => path.join(layout.root, 'node_modules', ...parts, 'index.js');
    const loaders: [string, 'cjs' | 'esm', string, string, string][] = [
      ['load-esm-package.mjs', 'esm', 'liftoff-plugin-evil', packageFile('liftoff-plugin-evil'), 'package-esm'],
      ['load-cjs-package.cjs', 'cjs', 'liftoff-plugin-evil-cjs', packageFile('liftoff-plugin-evil-cjs'), 'package-cjs'],
      ['load-inquirer-shadow.mjs', 'esm', '@inquirer/prompts', packageFile('@inquirer', 'prompts'), 'inquirer-shadow']
    ];
    for (const [name, format, specifier, expectedFile] of loaders) {
      await writeFile(path.join(layout.root, name), guardedLoader(format, specifier, expectedFile, path.join(resolutions, `${name}.json`)));
    }
    const expected = [
      ...layout.executables.map(({ id, relative }): [string, string] => [id, relative]),
      ...loaders.map(([name, , , , id]): [string, string] => [id, name])
    ];
    const runs: ControlRun[] = [];
    for (const [id, relative] of expected) {
      const run = runGeneratedFile(path.join(layout.root, ...relative.split('/')), layout.root, controlEnvironment(root));
      runs.push(run);
      expect(run.error, relative).toBeUndefined();
      expect(run.signal, relative).toBeNull();
      expect(run.status, relative).not.toBe(0);
      expect(run.stderr, relative).toContain(`plugin sentinel ${id} executed`);
      expect(await readFile(path.join(layout.markers, `${id}.executed`), 'utf8'), relative).toBe(`${id}\n`);
    }
    const verified: Record<string, unknown>[] = [];
    for (const [name, , specifier, expectedFile] of loaders) {
      const record = await resolutionRecord(path.join(resolutions, `${name}.json`));
      expect(record, name).toEqual({ resolved: await realpath(expectedFile), expected: await realpath(expectedFile), match: true });
      verified.push({ loader: name, specifier, match: record.match });
    }
    expect(await executedSentinels(layout.markers)).toEqual(expected.map(([id]) => `${id}.executed`).sort());
    recordEvidence(task.meta, {
      negativeControls: runs.map(({ file, status, signal }) => ({ file, status, signal })),
      verifiedResolutions: verified,
      markers: await executedSentinels(layout.markers)
    });
  });

  it('refuses to load a bare package that resolves anywhere but the owned sentinel (guard control)', async ({ task }) => {
    const root = await ownedRoot();
    const markers = path.join(root, 'markers');
    await mkdir(markers);
    const marker = (id: string): string => path.join(markers, `${id}.executed`);
    // Owned decoys stand in for an unexpected ancestor package; the guard must not load them.
    const plantPackage = async (directory: string, name: string, esm: boolean, id: string): Promise<string> => {
      const packageRoot = path.join(directory, 'node_modules', name);
      await mkdir(packageRoot, { recursive: true });
      await writeFile(path.join(packageRoot, 'package.json'), packageManifest(name, esm));
      await writeFile(path.join(packageRoot, 'index.js'), sentinelProgram(esm ? 'esm' : 'cjs', id, marker(id)));
      return path.join(packageRoot, 'index.js');
    };
    await plantPackage(root, 'liftoff-plugin-evil', true, 'decoy-esm');
    await plantPackage(root, 'liftoff-plugin-evil-cjs', false, 'decoy-cjs');
    const expectedRoot = path.join(root, 'guard', 'expected');
    const expectedEsm = await plantPackage(expectedRoot, 'liftoff-plugin-evil', true, 'expected-esm');
    const expectedCjs = await plantPackage(expectedRoot, 'liftoff-plugin-evil-cjs', false, 'expected-cjs');
    const guard = path.join(root, 'guard');
    const results = path.join(root, 'resolutions');
    await mkdir(results);
    await writeFile(path.join(guard, 'load.mjs'), guardedLoader('esm', 'liftoff-plugin-evil', expectedEsm, path.join(results, 'esm.json')));
    await writeFile(path.join(guard, 'load.cjs'), guardedLoader('cjs', 'liftoff-plugin-evil-cjs', expectedCjs, path.join(results, 'cjs.json')));
    const runs = [
      runGeneratedFile(path.join(guard, 'load.mjs'), guard, controlEnvironment(root)),
      runGeneratedFile(path.join(guard, 'load.cjs'), guard, controlEnvironment(root))
    ];
    for (const run of runs) expect([run.error, run.signal, run.status], run.file).toEqual([undefined, null, 3]);
    for (const [format, expectedFile, decoy] of [
      ['esm', expectedEsm, path.join(root, 'node_modules', 'liftoff-plugin-evil', 'index.js')],
      ['cjs', expectedCjs, path.join(root, 'node_modules', 'liftoff-plugin-evil-cjs', 'index.js')]
    ] as const) {
      expect(await resolutionRecord(path.join(results, `${format}.json`)), format).toEqual({
        resolved: await realpath(decoy),
        expected: await realpath(expectedFile),
        match: false
      });
    }
    expect(await executedSentinels(markers)).toEqual([]);
    recordEvidence(task.meta, {
      scope: 'resolution guard refusal with owned decoys; nothing outside the owned root is resolved or loaded',
      runs: runs.map(({ file, status, signal }) => ({ file, status, signal })),
      markers: []
    });
  });

  it('characterizes Node module lookup with NODE_PATH (Node evidence, not Liftoff startup isolation)', async ({ task }) => {
    const root = await ownedRoot();
    const layout = await plantSentinels(path.join(root, 'layout'), path.join(root, 'markers'));
    const probes = path.join(root, 'probes');
    await mkdir(probes);
    const result = (name: string): string => path.join(probes, `${name}.json`);
    const expectedCjs = path.join(layout.root, 'node_modules', 'liftoff-plugin-evil-cjs', 'index.js');
    await writeFile(path.join(probes, 'esm-probe.mjs'), resolutionOnlyProbe('liftoff-plugin-evil', result('esm')));
    await writeFile(path.join(probes, 'cjs-probe.cjs'), guardedLoader('cjs', 'liftoff-plugin-evil-cjs', expectedCjs, result('cjs')));
    const env = controlEnvironment(root, { NODE_PATH: path.join(layout.root, 'node_modules') });
    const esm = runGeneratedFile(path.join(probes, 'esm-probe.mjs'), probes, env);
    const cjs = runGeneratedFile(path.join(probes, 'cjs-probe.cjs'), probes, env);
    // ESM resolution ignores NODE_PATH: nothing resolves and nothing is loaded.
    expect([esm.error, esm.signal, esm.status]).toEqual([undefined, null, 0]);
    expect(await resolutionRecord(result('esm'))).toEqual({ resolved: null, code: 'ERR_MODULE_NOT_FOUND' });
    // CommonJS resolution honors NODE_PATH; only the verified owned sentinel is then loaded.
    expect([cjs.error, cjs.signal]).toEqual([undefined, null]);
    expect(cjs.status).not.toBe(0);
    expect(cjs.stderr).toContain('plugin sentinel package-cjs executed');
    expect(await resolutionRecord(result('cjs'))).toEqual({
      resolved: await realpath(expectedCjs),
      expected: await realpath(expectedCjs),
      match: true
    });
    expect(await executedSentinels(layout.markers)).toEqual(['package-cjs.executed']);
    recordEvidence(task.meta, {
      scope: 'Node module lookup characterization with generated owned probes; not Liftoff startup isolation',
      esm: { status: esm.status, resolved: null, code: 'ERR_MODULE_NOT_FOUND', loaded: false },
      cjs: { status: cjs.status, resolvedToOwnedSentinel: true, loaded: 'package-cjs' },
      markers: await executedSentinels(layout.markers)
    });
  });

  it('keeps project-independent commands byte-identical beside planted plugin content', async ({ task }) => {
    const root = await ownedRoot();
    const clean = path.join(root, 'clean');
    await mkdir(clean);
    const layout = await plantSentinels(path.join(root, 'planted'), path.join(root, 'markers'));
    const before = await captureTreeState(layout.root);
    const results: Record<string, unknown>[] = [];
    for (const argv of [['help'], ['--version'], ['help', 'init'], ['patterns'], ['providers'], ['regions'], ['repair', '--capabilities', '--json']]) {
      const baseline = await invoke(argv, clean);
      const planted = await invoke(argv, layout.root);
      expect(baseline.code, argv.join(' ')).toBe(0);
      expect(normalizedOutput(planted, layout.root), argv.join(' ')).toBe(normalizedOutput(baseline, clean));
      expect(sentinelReferences(runnerCommands(planted.runner)), argv.join(' ')).toEqual([]);
      results.push({ argv, code: planted.code, runnerCalls: planted.runner.calls.length });
    }
    expect(await captureTreeState(layout.root)).toEqual(before);
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    recordEvidence(task.meta, { commands: results, markers: [] });
  });

  it('rejects plugin-shaped selections with precise errors before generation', async ({ task }) => {
    const root = await ownedRoot();
    const layout = await plantSentinels(path.join(root, 'planted'), path.join(root, 'markers'));
    const before = await captureTreeState(layout.root);
    const moduleUrl = pathToFileURL(path.join(layout.root, '.liftoff', 'plugins', 'evil.mjs')).href;
    const cases: [string[], RegExp][] = [
      [projectArgs({ '--api': './plugins/evil/index.js' }), /Unknown API stack: \.\/plugins\/evil\/index\.js\./],
      [projectArgs({ '--api': 'liftoff-plugin-evil' }), /Unknown API stack: liftoff-plugin-evil\./],
      [projectArgs({ '--cloud': './liftoff.config.mjs' }), /Unknown cloud provider: \.\/liftoff\.config\.mjs\./],
      [projectArgs({ '--spec': moduleUrl }), /Unknown spec-driven workflow: file:/],
      [projectArgs({ '--agents': './plugins/evil' }), /Unknown AI coding agent: \.\/plugins\/evil\./],
      [projectArgs({ '--governance': 'liftoff-plugin-evil' }), /Unknown repository governance profile: liftoff-plugin-evil\./],
      [projectArgs({ '--type': 'genai', '--api': null, '--pattern': './.liftoff/plugins/evil.ts' }), /Unknown GenAI pattern: \.\/\.liftoff\/plugins\/evil\.ts\./]
    ];
    const results: Record<string, unknown>[] = [];
    for (const [flags, message] of cases) {
      const result = await invoke(['init', 'app', ...flags], layout.root);
      const label = flags.join(' ');
      expect(result.code, label).not.toBe(0);
      expect(`${result.out}${result.err}`, label).toMatch(message);
      expect(result.runner.calls, label).toEqual([gitRootDiscovery]);
      expect(sentinelReferences(runnerCommands(result.runner)), label).toEqual([]);
      expect(await captureTreeState(layout.root), label).toEqual(before);
      results.push({ flags: label.split(layout.root).join('<root>'), code: result.code, message: message.source, runnerCalls: result.runner.calls });
    }
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    recordEvidence(task.meta, { selections: results, markers: [] });
  });

  it('treats plugin-looking configuration as data and never imports configuration code', async ({ task }) => {
    const root = await ownedRoot();
    const layout = await plantSentinels(path.join(root, 'planted'), path.join(root, 'markers'));
    await writeFile(path.join(layout.root, 'plugin-config.json'), `${JSON.stringify({ projectName: 'app', pluginPath: './plugins/evil/index.js' })}\n`);
    const before = await captureTreeState(layout.root);
    const cases: [string, RegExp][] = [
      ['liftoff.plugins.json', /Unknown configuration field: plugins\./],
      ['plugin-config.json', /Unknown configuration field: pluginPath\./],
      ['liftoff.config.mjs', /Unable to parse configuration .*liftoff\.config\.mjs: /],
      ['liftoff.config.js', /Unable to parse configuration .*liftoff\.config\.js: /]
    ];
    const results: Record<string, unknown>[] = [];
    for (const [config, message] of cases) {
      const result = await invoke(['init', 'app', '--config', config, '--yes'], layout.root);
      expect(result.code, config).not.toBe(0);
      expect(`${result.out}${result.err}`, config).toMatch(message);
      expect(result.runner.calls, config).toEqual([]);
      expect(await captureTreeState(layout.root), config).toEqual(before);
      results.push({ config, code: result.code, message: message.source });
    }
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    recordEvidence(task.meta, { configurations: results, markers: [] });
  });

  it('generates identical projects beside planted content and never runs content planted in a project', async ({ task }) => {
    const root = await ownedRoot();
    const cleanRoot = path.join(root, 'clean');
    await mkdir(cleanRoot);
    const layout = await plantSentinels(path.join(root, 'planted'), path.join(root, 'markers'));
    const cleanHome = path.join(root, 'clean-home');
    const plantedHome = path.join(root, 'planted-home');
    const cleanInit = await invoke(['init', 'app', ...projectArgs()], cleanRoot, { previewHome: cleanHome });
    const plantedInit = await invoke(['init', 'app', ...projectArgs()], layout.root, { previewHome: plantedHome });
    expect(cleanInit.code, cleanInit.out + cleanInit.err).toBe(0);
    expect(plantedInit.code, plantedInit.out + plantedInit.err).toBe(0);
    const cleanProject = path.join(cleanRoot, 'app');
    const plantedProject = path.join(layout.root, 'app');
    expect(await captureTreeState(plantedProject)).toEqual(await captureTreeState(cleanProject));
    expect(await readFile(path.join(plantedProject, 'backend', 'package.json'), 'utf8')).not.toContain('poisoned-sentinel');
    expect(await normalizedCommands(plantedInit.runner, layout.root)).toEqual(await normalizedCommands(cleanInit.runner, cleanRoot));
    expect(sentinelReferences(runnerCommands(plantedInit.runner))).toEqual([]);

    const projectLayout = await plantSentinels(plantedProject, path.join(root, 'project-markers'));
    const results: Record<string, unknown>[] = [];
    for (const argv of [['validate', '--json'], ['update', '--check', '--json'], ['doctor', '--json'], ['governance', 'verify', '--json']]) {
      const baseline = await invoke(argv, cleanProject, { previewHome: cleanHome });
      const planted = await invoke(argv, plantedProject, { previewHome: plantedHome });
      const label = argv.join(' ');
      expect(planted.code, `${label}\n${planted.out}${planted.err}`).toBe(baseline.code);
      expect(sentinelReferences(runnerCommands(planted.runner)), label).toEqual([]);
      results.push({ argv, code: planted.code, baselineCode: baseline.code, runnerCalls: planted.runner.calls.length });
    }
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(await executedSentinels(projectLayout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    // The planted project files stayed live throughout: executing one directly still trips its marker.
    const live = runGeneratedFile(path.join(plantedProject, '.liftoff', 'plugins', 'evil.mjs'), plantedProject, controlEnvironment(root));
    expect(live.status).not.toBe(0);
    expect(await executedSentinels(projectLayout.markers)).toEqual(['liftoff-mjs.executed']);
    recordEvidence(task.meta, {
      init: { cleanCode: cleanInit.code, plantedCode: plantedInit.code, identicalTree: true, runnerCalls: plantedInit.runner.calls.length },
      maintenance: results,
      liveSentinelAfterwards: { file: live.file, status: live.status, marker: 'liftoff-mjs.executed' }
    });
  }, 120_000);

  it('copies legacy plugin content as inert bytes during migration and characterizes exclusions', async ({ task }) => {
    const root = await ownedRoot();
    const legacy = path.join(root, 'legacy');
    await mkdir(legacy);
    await writeFile(path.join(legacy, 'package.json'), '{"dependencies":{"fastify":"5.0.0"}}\n');
    await writeFile(path.join(legacy, 'app.js'), 'export const legacy = true;\n');
    const layout = await plantSentinels(legacy, path.join(root, 'markers'));
    const before = await captureTreeState(legacy);
    const migrated = await invoke(['migrate', legacy, '--project', 'adopted-app', ...projectArgs(), '--governance', 'none'], root);
    expect(migrated.code, migrated.out + migrated.err).toBe(0);
    expect(await captureTreeState(legacy)).toEqual(before);
    const copy = path.join(root, 'adopted-app', 'migration', 'legacy');
    const copied = [...(await captureTreeState(copy)).values()]
      .filter((entry) => entry.type === 'file')
      .map((entry) => entry.pathParts.join('/'))
      .sort();
    // Migration's existing directory rule excludes node_modules; every other planted file is copied.
    const excluded = layout.files.filter((relative) => relative.startsWith('node_modules/'));
    expect(excluded).toHaveLength(6);
    expect(copied).toEqual([...layout.files.filter((relative) => !excluded.includes(relative)), 'app.js', 'package.json'].sort());
    for (const relative of copied) {
      expect(await readFile(path.join(copy, ...relative.split('/'))), relative)
        .toEqual(await readFile(path.join(legacy, ...relative.split('/'))));
    }
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    expect(sentinelReferences(runnerCommands(migrated.runner))).toEqual([]);
    recordEvidence(task.meta, { included: copied, excludedByMigrationDirectoryRule: excluded, markers: [] });
  }, 120_000);

  it('ignores plugin-path environment settings at runtime (runtime environment only; Node startup resolution excluded)', async ({ task }) => {
    const root = await ownedRoot();
    const layout = await plantSentinels(path.join(root, 'planted'), path.join(root, 'markers'));
    const init = await invoke(['init', 'app', ...projectArgs()], layout.root);
    expect(init.code, init.out + init.err).toBe(0);
    const project = path.join(layout.root, 'app');
    const pluginEnvironment = {
      LIFTOFF_PLUGIN_PATH: path.join(layout.root, 'plugins', 'evil', 'index.js'),
      LIFTOFF_PLUGINS: 'liftoff-plugin-evil',
      LIFTOFF_PLUGIN_DIR: path.join(layout.root, '.liftoff', 'plugins'),
      NODE_PATH: path.join(layout.root, 'node_modules')
    };
    const commands: [string[], string][] = [
      [['patterns'], layout.root],
      [['repair', '--capabilities', '--json'], layout.root],
      [['init', 'other', ...projectArgs({ '--api': 'liftoff-plugin-evil' })], layout.root],
      [['validate', '--json'], project]
    ];
    const baseline: string[] = [];
    for (const [argv, cwd] of commands) baseline.push(normalizedOutput(await invoke(argv, cwd), root));
    // Both the context environment and process.env; NODE_PATH is only read by Node at startup.
    for (const [key, value] of Object.entries(pluginEnvironment)) vi.stubEnv(key, value);
    const results: Record<string, unknown>[] = [];
    for (const [index, [argv, cwd]] of commands.entries()) {
      const result = await invoke(argv, cwd, { env: pluginEnvironment });
      expect(normalizedOutput(result, root), argv.join(' ')).toBe(baseline[index]);
      expect(sentinelReferences(runnerCommands(result.runner)), argv.join(' ')).toEqual([]);
      const inherited = [...new Set(result.runner.callDetails.flatMap(({ options }) =>
        Object.keys(pluginEnvironment).filter((key) => options?.env?.[key] !== undefined)))].sort();
      results.push({ command: argv.slice(0, 2).join(' '), code: result.code, runnerCalls: result.runner.calls, inheritedByExternalCommands: inherited });
    }
    expect(await executedSentinels(layout.markers)).toEqual([]);
    expect(sentinelFlagValue()).toBeUndefined();
    recordEvidence(task.meta, {
      scope: 'runtime environment only; Node startup resolution (NODE_PATH, NODE_OPTIONS) is excluded',
      variables: Object.keys(pluginEnvironment),
      commands: results,
      markers: []
    });
  }, 120_000);
});

async function normalizedCommands(runner: ReadyInitRunner, ...roots: string[]): Promise<unknown> {
  let text = JSON.stringify(runnerCommands(runner));
  for (const root of roots) {
    const spellings = [...new Set([await realpath(root), root])].sort((left, right) => right.length - left.length);
    for (const spelling of spellings) text = text.split(JSON.stringify(spelling).slice(1, -1)).join('<root>');
  }
  // Framework initializers run in a fresh mkdtemp staging directory; only its random suffix varies.
  return JSON.parse(text.replace(/liftoff-init-[A-Za-z0-9]{6}/g, 'liftoff-init-<staging>')) as unknown;
}
