import type { AddArtifact } from '../../template-types.js';
import type { ApiProjectPlan } from '../../domain/project/contracts.js';
import type { ExternalCommand } from '../../domain/project/contracts.js';
import { formatCommand } from '../../process-runner.js';
import { functionWorkerName } from './values.js';
import { genAiPattern } from './values.js';
import { hasFunctionWorker } from './values.js';
import type { ProjectPlan } from '../../domain/project/contracts.js';

export function addSpecWorkflowArtifacts(
  addSeed: AddArtifact,
  addFramework: AddArtifact,
  plan: ProjectPlan
): void {
  if (plan.specWorkflow.id === 'openspec') {
    const changeName = `bootstrap-${plan.safeProjectName}`;
    addSeed('openspec-config', 'seed', ['openspec', 'config.yaml'], renderOpenSpecConfig(plan));
    addSeed('openspec-seed-change-metadata', 'seed', ['openspec', 'changes', changeName, '.openspec.yaml'], 'schema: spec-driven');
    addSeed('openspec-seed-proposal', 'seed', ['openspec', 'changes', changeName, 'proposal.md'], renderSeedProposal(plan));
    addSeed('openspec-seed-design', 'seed', ['openspec', 'changes', changeName, 'design.md'], renderSeedDesign(plan));
    addSeed('openspec-seed-tasks', 'seed', ['openspec', 'changes', changeName, 'tasks.md'], renderSeedTasks(plan));
    addSeed('openspec-seed-spec', 'seed', ['openspec', 'changes', changeName, 'specs', seedCapabilityId(plan), 'spec.md'], renderSeedSpec(plan));
    addSeed('openspec-spec-placeholder', 'seed', ['openspec', 'specs', '.gitkeep'], '');
  } else {
    addSeed('spec-kit-constitution', 'seed', ['.specify', 'memory', 'constitution.md'], renderSpecKitConstitution(plan));
    addFramework('spec-kit-spec-template', 'framework', ['.specify', 'templates', 'spec-template.md'], renderSpecKitSpecTemplate());
    addFramework('spec-kit-plan-template', 'framework', ['.specify', 'templates', 'plan-template.md'], renderSpecKitPlanTemplate());
    addSeed('specs-placeholder', 'seed', ['specs', '.gitkeep'], '');
    const bootstrap = ['specs', '000-liftoff-bootstrap'];
    addSeed('spec-kit-bootstrap-spec', 'seed', [...bootstrap, 'spec.md'], renderSpecKitBootstrapSpec(plan));
    addSeed('spec-kit-bootstrap-plan', 'seed', [...bootstrap, 'plan.md'], renderSpecKitBootstrapPlan(plan));
    addSeed('spec-kit-bootstrap-tasks', 'seed', [...bootstrap, 'tasks.md'], renderSpecKitBootstrapTasks(plan));
  }
}

export function renderOpenSpecCopilotConfig(plan: ProjectPlan): string {
  return plan.agents.some((agent) => agent.id === 'github-copilot')
    ? `
githubCopilot:
  cloudAgent: ${plan.copilotCloud}
`
    : '\n';
}

export function renderOpenSpecConfig(plan: ApiProjectPlan): string {
  const frontendRule = plan.includeFrontend ? '\n    - Keep frontend code under frontend.' : '';
  if (plan.workload === 'standard') {
    const backendRule = plan.apiStack.id === 'python-fastapi'
      ? 'Keep backend API code under backend/apis.'
      : plan.apiStack.id === 'node-fastify'
        ? 'Keep backend API code under backend/src.'
        : 'Keep the Go entrypoint under backend/cmd/api and reusable code under backend/internal.';
    return `schema: spec-driven${renderOpenSpecCopilotConfig(plan)}

context: |
  Project generated by Mission Control Liftoff.
  Project type: Standard application.
  API stack: ${plan.apiStack.label}.
  Database tooling: ${plan.apiStack.databaseTooling}.
  API developer portal: Scalar.
  Infrastructure: OpenTofu.
  Primary cloud: Azure (${plan.region.slug}).
  Local development: Docker Compose.
  Database: PostgreSQL.
  Cache and local messaging: Redis.
  Environments: ${plan.environments.map((environment) => environment.id).join(', ')}.

rules:
  specs:
    - Requirements must describe observable product behavior.
    - Cloud behavior must identify environment differences for generated environments.
  design:
    - Use ${plan.apiStack.framework} for backend APIs.
    - Use ${plan.apiStack.databaseTooling} for database access and migrations.
    - Use OpenTofu for infrastructure changes.${frontendRule}
    - ${backendRule}
    - Keep database artifacts under database.
  tasks:
    - Include local Docker Compose verification.
    - Include OpenTofu validation for generated infrastructure.
`;
  }

  const pattern = genAiPattern(plan);
  const functionsContext = hasFunctionWorker(plan) ? `
  Azure Functions worker: functions/${functionWorkerName(plan)}.` : '';
  const functionsRule = hasFunctionWorker(plan) ? `
    - Keep Azure Functions trigger adapters under functions/${functionWorkerName(plan)}.
    - Keep reusable GenAI orchestration under backend/orchestration.` : '';
  return `schema: spec-driven${renderOpenSpecCopilotConfig(plan)}

context: |
  Project generated by Mission Control Liftoff.
  GenAI pattern: ${pattern.label}
  Application framework: FastAPI + PydanticAI.
  API developer portal: Scalar.
  Infrastructure: OpenTofu.
  Primary cloud: Azure (${plan.region.slug}).
  Local development: Docker Compose.
  Database: PostgreSQL with Alembic migrations.
  Cache and local messaging: Redis.
  Observability: Langfuse.
  Environments: ${plan.environments.map((environment) => environment.id).join(', ')}.
${functionsContext}

rules:
  specs:
    - Requirements must describe observable product behavior.
    - Cloud behavior must identify environment differences for generated environments.
  design:
    - Use PydanticAI for orchestration logic.
    - Use Pydantic settings models for runtime configuration.
    - Use OpenTofu for infrastructure changes.${frontendRule}
    - Keep backend API code under backend/apis.
${functionsRule}
    - Keep database artifacts under database.
  tasks:
    - Include local Docker Compose verification.
    - Include OpenTofu validation for generated infrastructure.
`;
}

export function renderSeedProposal(plan: ApiProjectPlan): string {
  const capability = seedCapabilityId(plan);
  if (plan.workload === 'standard') {
    return `## Why

Bootstrap the generated ${plan.apiStack.label} standard application baseline created by Mission Control Liftoff.

## What Changes

- Establish the approved backend, infrastructure, local development, and governance baseline.
- Confirm that domain-specific product behavior is deferred to follow-up spec-driven changes.

## Capabilities

### New Capabilities

- \`${capability}\`: Generated standard application baseline for this Liftoff project.

### Modified Capabilities

- None.

## Impact

- Generated ${plan.apiStack.label} backend, OpenTofu infrastructure, Docker Compose local development, and governance files.
`;
  }

  const pattern = genAiPattern(plan);
  const functionsChange = hasFunctionWorker(plan) ? '\n- Establish Azure Functions worker trigger adapters for event-driven processing.' : '';
  return `## Why

Bootstrap the generated ${pattern.label} application baseline created by Mission Control Liftoff.

## What Changes

- Establish the approved backend, infrastructure, local development, and governance baseline.
- Confirm that domain-specific product behavior is deferred to follow-up spec-driven changes.
${functionsChange}

## Capabilities

### New Capabilities

- \`${capability}\`: Generated application baseline for this Liftoff project.

### Modified Capabilities

- None.

## Impact

- Generated FastAPI/PydanticAI backend, OpenTofu infrastructure, Docker Compose local development, and governance files.
`;
}

export function renderSeedDesign(plan: ApiProjectPlan): string {
  if (plan.workload === 'standard') {
    return `## Context

This standard project was generated with Liftoff using ${plan.apiStack.label}, Azure, OpenTofu, and ${plan.specWorkflow.label}.

## Goals / Non-Goals

**Goals:**

- Keep the generated baseline aligned to the approved Mission Control stack.
- Verify only deterministic local scaffold checks before archiving this bootstrap change.

**Non-Goals:**

- Define domain-specific product behavior in the bootstrap change.
- Deploy infrastructure, start containers, mutate GitHub, or perform cloud plan/apply operations.

## Decisions

- Use ${plan.apiStack.framework} for backend APIs.
- Use ${plan.apiStack.databaseTooling} for PostgreSQL integration.
- Use OpenTofu for Azure infrastructure.
- Use Docker Compose for local development.

## Risks / Trade-offs

- Follow-up product changes own real business behavior; this seed only proves the generated local baseline is coherent.
`;
  }

  const pattern = genAiPattern(plan);
  const functionsDecision = hasFunctionWorker(plan) ? '\n- Keep Azure Functions trigger adapters under functions/' + functionWorkerName(plan) + ' and shared GenAI logic under backend/orchestration.' : '';
  return `## Context

This project was generated with Liftoff using ${pattern.label}, Azure, OpenTofu, and ${plan.specWorkflow.label}.

## Goals / Non-Goals

**Goals:**

- Keep the generated baseline aligned to the approved Mission Control stack.
- Verify only deterministic local scaffold checks before archiving this bootstrap change.

**Non-Goals:**

- Define domain-specific product behavior in the bootstrap change.
- Deploy infrastructure, start containers, mutate GitHub, or perform cloud plan/apply operations.

## Decisions

- Use FastAPI and PydanticAI for backend APIs and orchestration.
- Use OpenTofu for Azure infrastructure.
- Use Docker Compose for local development.
${functionsDecision}

## Risks / Trade-offs

- Follow-up product changes own real business behavior; this seed only proves the generated local baseline is coherent.
`;
}

export function seedCapabilityId(plan: ProjectPlan): string {
  if (plan.workload === 'standard') {
    return `${plan.apiStack.id}-application-baseline`;
  }
  return `${genAiPattern(plan).id}-application-baseline`;
}

export function seedCapabilityPurpose(plan: ProjectPlan): string {
  if (plan.workload === 'standard') {
    return `Define the generated ${plan.apiStack.label} application baseline that setup verifies and archives before domain-specific implementation or deployment begins.`;
  }
  return `Define the generated ${genAiPattern(plan).label} application baseline that setup verifies and archives before domain-specific implementation or deployment begins.`;
}

export function renderSeedSpec(plan: ProjectPlan): string {
  const capability = seedCapabilityId(plan);
  const purpose = seedCapabilityPurpose(plan);
  if (plan.workload === 'standard') {
    return `## Purpose

${purpose}

## ADDED Requirements

### Requirement: Generated ${plan.apiStack.label} baseline is locally verifiable
The bootstrap seed SHALL describe only the generated ${plan.apiStack.label} backend, optional frontend, Docker Compose, OpenTofu, workflow configuration, and governance baseline. Domain-specific product behavior SHALL be deferred to later changes.

#### Scenario: Generated baseline is present
- **WHEN** the \`bootstrap-${plan.safeProjectName}\` change is generated
- **THEN** it declares the \`${capability}\` capability
- **AND** the generated backend, database, Docker Compose, OpenTofu, workflow, and governance files are in scope

#### Scenario: Product behavior is deferred
- **WHEN** the bootstrap change is completed
- **THEN** no domain-specific API, data model, UI, deployment, GitHub, or cloud mutation is introduced

#### Scenario: Local baseline checks pass
- **WHEN** deterministic setup verifies the seed
- **THEN** \`liftoff validate\`, backend tests, Docker Compose configuration validation, OpenTofu formatting, backend-disabled initialization, OpenTofu validation, and strict OpenSpec validation have passed
- **AND** frontend checks are run only when a frontend was generated
`;
  }

  const pattern = genAiPattern(plan);
  const worker = hasFunctionWorker(plan)
    ? 'Azure Functions worker, '
    : '';
  return `## Purpose

${purpose}

## ADDED Requirements

### Requirement: Generated ${pattern.label} baseline is locally verifiable
The bootstrap seed SHALL describe only the generated FastAPI/PydanticAI backend, ${worker}optional frontend, Docker Compose, OpenTofu, workflow configuration, and governance baseline. Domain-specific product behavior SHALL be deferred to later changes.

#### Scenario: Generated baseline is present
- **WHEN** the \`bootstrap-${plan.safeProjectName}\` change is generated
- **THEN** it declares the \`${capability}\` capability
- **AND** the generated GenAI backend, database, Docker Compose, OpenTofu, workflow, governance${hasFunctionWorker(plan) ? ', and worker' : ''} files are in scope

#### Scenario: Product behavior is deferred
- **WHEN** the bootstrap change is completed
- **THEN** no domain-specific prompts, tools, retrieval corpus, agent policy, UI, deployment, GitHub, or cloud mutation is introduced

#### Scenario: Local baseline checks pass
- **WHEN** deterministic setup verifies the seed
- **THEN** \`liftoff validate\`, backend tests,${hasFunctionWorker(plan) ? ' worker tests,' : ''} Docker Compose configuration validation, OpenTofu formatting, backend-disabled initialization, OpenTofu validation, and strict OpenSpec validation have passed
- **AND** frontend checks are run only when a frontend was generated
`;
}

export interface SeedTaskCheck {
  id: string;
  label: string;
  command?: ExternalCommand;
  cwd?: readonly string[];
  inapplicable?: string;
}

export function seedTaskChecks(plan: ProjectPlan): SeedTaskCheck[] {
  const checks: SeedTaskCheck[] = [
    {
      id: '2.1',
      label: 'Run Liftoff manifest validation',
      command: { executable: 'liftoff', args: ['validate'] }
    }
  ];
  if (plan.workload === 'genai' || plan.apiStack.id === 'python-fastapi') {
    checks.push({
      id: '2.2',
      label: 'Run backend tests',
      command: { executable: 'uv', args: ['run', '--project', 'backend', 'python', '-m', 'pytest', '-q', 'backend/tests'] }
    });
  } else if (plan.apiStack.id === 'node-fastify') {
    checks.push({
      id: '2.2',
      label: 'Run backend tests',
      command: { executable: 'npm', args: ['test'] },
      cwd: ['backend']
    });
  } else {
    checks.push({
      id: '2.2',
      label: 'Run backend tests',
      command: { executable: 'go', args: ['test', './...'] },
      cwd: ['backend']
    });
  }

  if (plan.workload === 'genai' && hasFunctionWorker(plan)) {
    checks.push({
      id: '2.3',
      label: 'Run generated worker tests',
      command: { executable: 'uv', args: ['run', '--project', '../../backend', '--directory', '.', 'python', '-m', 'pytest', '-q'] },
      cwd: ['functions', functionWorkerName(plan)]
    });
  } else {
    checks.push({
      id: '2.3',
      label: 'Record worker tests as inapplicable',
      inapplicable: 'no generated worker boundary is present'
    });
  }

  if (plan.includeFrontend) {
    checks.push({
      id: '2.4',
      label: 'Run frontend build',
      command: { executable: 'npm', args: ['run', 'build'] },
      cwd: ['frontend']
    });
  } else {
    checks.push({
      id: '2.4',
      label: 'Record frontend build as inapplicable',
      inapplicable: 'no generated frontend is present'
    });
  }

  {
    checks.push({
      id: '2.5',
      label: 'Validate Docker Compose configuration without startup',
      command: { executable: 'docker', args: ['compose', 'config', '-q'] }
    });
    checks.push({
      id: '2.6',
      label: 'Check OpenTofu formatting',
      command: { executable: 'tofu', args: ['fmt', '-check', '-recursive'] },
      cwd: ['infrastructure', 'opentofu', 'azure']
    });
    for (const [index, environment] of plan.environments.entries()) {
      const cwd = ['infrastructure', 'opentofu', 'azure', 'environments', environment.id];
      checks.push({
        id: `2.7.${index + 1}`,
        label: `Initialize ${environment.id} OpenTofu without a backend`,
        command: { executable: 'tofu', args: ['init', '-backend=false'] },
        cwd
      });
      checks.push({
        id: `2.8.${index + 1}`,
        label: `Validate ${environment.id} OpenTofu without plan or apply`,
        command: { executable: 'tofu', args: ['validate'] },
        cwd
      });
    }
  }

  checks.push({
    id: '2.9',
    label: 'Run strict OpenSpec validation',
    command: { executable: 'openspec', args: ['validate', `bootstrap-${plan.safeProjectName}`, '--strict'] }
  });
  return checks;
}

export function renderSpecKitBootstrapSpec(plan: ApiProjectPlan): string {
    return `# Generated-project baseline: ${plan.projectName}

  Bootstrap identity: \`000-liftoff-bootstrap\`.

  ## Scope

  Verify the generated ${plan.apiStack.label} backend, ${plan.includeFrontend ? 'Vue frontend, ' : ''}database metadata,
  container configuration, independent OpenTofu environment roots, and local workflow files.
  This one-time project-owned seed is not a product feature or an active governance change.

  ## Requirements

  - Read this real spec, its sibling \`plan.md\`, and \`tasks.md\`; framework templates are not project proof.
  - Validate official Spec Kit initialization markers separately; this bundle does not replace them.
  - Use already-installed locked dependencies, or install applicable dependencies with explicit consent, and run the local baseline.
  - Check every selected environment: ${plan.environments.map(({ id }) => id).join(', ')}.
  - Preserve project-owned files. Do not create a Git branch, OpenSpec tree, or external archive.
  - Do not claim retrieval, history, tools, prompt loading, coordination, fine-tuning, workflow stages,
    incremental streaming, live deployment, or production governance completion.

  ## Success criteria

  All applicable local checks have passed on the current inputs, absent components are explicitly
  inapplicable, and only then is the local bootstrap task projection finalized with a bound receipt.
  Unchecked tasks, generated files, and framework plan templates are not completion evidence.
  `.replace(/^ {2}/gm, '');
  }

  export function renderSpecKitBootstrapPlan(plan: ApiProjectPlan): string {
    const backend = plan.workload === 'genai' || plan.apiStack.id === 'python-fastapi'
      ? `uv sync --frozen --project backend --extra test${hasFunctionWorker(plan) ? ' --extra functions' : ''}`
      : plan.apiStack.id === 'node-fastify'
        ? 'npm ci && npm run build (from backend/)'
        : 'go mod download (from backend/)';
    return `# Local bootstrap implementation plan

  Bootstrap identity: \`000-liftoff-bootstrap\`.
  Source specification: \`specs/000-liftoff-bootstrap/spec.md\`.

  ## Preparation

  Review the generated files and official Spec Kit markers. Copy \`.env.example\` to \`.env\`
  for the documented local settings; do not commit local configuration or credentials.
  ${plan.workload === 'standard' && plan.apiStack.id === 'go-huma' ? 'For native Go startup, also copy `runtime.config.example.json` to root `runtime.config.json`.\n' : ''}
  Dependency installation requires its own consent: \`${backend}\`.
  ${plan.includeFrontend ? 'Install frontend dependencies with `npm ci` from `frontend/`.\n' : ''}
  ## Verification

  Run Liftoff validation, backend${hasFunctionWorker(plan) ? ' and worker' : ''} tests,
  ${plan.includeFrontend ? 'the frontend build, ' : ''}Docker Compose configuration validation,
  OpenTofu formatting, and backend-disabled initialization plus validation of every selected root:
  ${plan.environments.map(({ id }) => `- \`infrastructure/opentofu/azure/environments/${id}/\``).join('\n')}

  These checks do not start containers, invoke a model, provision resources, or mutate GitHub.
  Operational OpenTofu initialization must use the configured backend; only this local baseline
  uses \`-backend=false\`.

  ## Local handoff

  After all applicable checks succeed, explicitly finalize the task projection and record the local
  baseline receipt. The setup phase named \`seed-archived\` denotes this local handoff, not an archive
  command. Missing older bundles require separate reviewed adoption, never implicit update.
  `.replace(/^ {2}/gm, '');
  }

  export function renderSpecKitBootstrapTasks(plan: ApiProjectPlan): string {
    const checks = seedTaskChecks(plan).filter(({ id }) => id !== '2.9');
    return `# Local bootstrap tasks

  Bootstrap identity: \`000-liftoff-bootstrap\`.
  Read \`spec.md\` and \`plan.md\` in this directory before running checks.

  - [ ] B001 Review the real bootstrap spec, plan, generated files, runtime configuration, and separately validated official Spec Kit markers.
  - [ ] B002 Use already-installed locked dependencies, or install them with explicit consent, using the preparation commands in plan.md.
  - [ ] B003 Run Liftoff validation and backend${hasFunctionWorker(plan) ? ' plus worker' : ''} tests without external services.
  - [ ] B004 ${plan.includeFrontend ? 'Build the generated frontend.' : 'Record frontend build as inapplicable because no frontend was generated.'}
  - [ ] B005 Validate Docker Compose configuration and every selected independent OpenTofu root without starting containers or using live providers.
  - [ ] B006 Only after every applicable check passes, explicitly finalize this local task projection and record the current-input-bound baseline receipt; no Git branch or external archive is created.

  ## Required local checks

  ${checks.map((check) => {
    if (!check.command) return `- ${check.label}: inapplicable because ${check.inapplicable}.`;
    return `- ${check.label}${check.cwd ? ` from \`${check.cwd.join('/')}\`` : ''}: \`${formatCommand(check.command)}\`.`;
  }).join('\n')}

  Task checkboxes are a projection after successful verification, not an input proving success.
  Read-only status, resume, assessment, and verification do not mark tasks complete.
  `.replace(/^ {2}/gm, '');
  }

export function renderSeedTaskCheck(check: SeedTaskCheck): string {
  if (!check.command) {
    return `- [ ] ${check.id} ${check.label}: inapplicable because ${check.inapplicable}.`;
  }
  const cwd = check.cwd && check.cwd.length > 0 ? ` from \`${check.cwd.join('/')}\`` : '';
  return `- [ ] ${check.id} ${check.label}${cwd}: \`${formatCommand(check.command)}\`.`;
}

export function renderSeedTasks(plan: ProjectPlan): string {
  return `## 1. Bootstrap Scope

- [ ] 1.1 Confirm generated baseline files, \`liftoff.manifest.json\`, OpenSpec configuration, and the \`${seedCapabilityId(plan)}\` delta spec are present.
- [ ] 1.2 Confirm domain-specific product behavior is deferred to follow-up OpenSpec changes; do not replace generated placeholders in this bootstrap change.

## 2. Local Baseline Checks

${seedTaskChecks(plan).map(renderSeedTaskCheck).join('\n')}

## 3. Completion

- [ ] 3.1 After every applicable local check succeeds and every absent component is recorded inapplicable, archive with \`openspec archive bootstrap-${plan.safeProjectName} --yes\`, then require \`openspec validate --all --strict\` to pass. OpenSpec archive updates the main specs as part of archive; do not pass \`--skip-specs\`.

No task in this bootstrap seed starts containers, runs cloud plan/apply, mutates GitHub, or implements domain-specific product behavior.
`;
}

export function renderSpecKitConstitution(plan: ApiProjectPlan): string {
  if (plan.workload === 'standard') {
    const backendLayout = plan.apiStack.id === 'python-fastapi'
      ? 'backend/apis'
      : plan.apiStack.id === 'node-fastify' ? 'backend/src' : 'backend/cmd/api and backend/internal';
    return `# Mission Control Liftoff Constitution

## Principle 1: Approved Application Stack
Generated backend services MUST use ${plan.apiStack.framework}, ${plan.apiStack.databaseTooling}, and Scalar for API documentation.

## Principle 2: Standard Project Layout
Backend APIs live under ${backendLayout}. Database artifacts live under database.${plan.includeFrontend ? ' Frontend code lives under frontend.' : ''}

## Principle 3: Infrastructure As Code
Cloud infrastructure MUST be defined with OpenTofu. Azure is the supported V1 provider.

## Principle 4: Local Development Parity
Projects MUST include Docker Compose for local development with PostgreSQL, Redis, local blob storage, and local messaging behavior.

## Principle 5: Observability And Operations
Services MUST use structured logging and environment-specific configuration for ${plan.environments.map((environment) => environment.id).join(', ')}.
`;
  }

  const functionsLayout = plan.workload === 'genai' && hasFunctionWorker(plan)
    ? ` Azure Functions trigger adapters live under functions/${functionWorkerName(plan)} and call shared orchestration from backend/orchestration.`
    : '';
  return `# Mission Control Liftoff Constitution

## Principle 1: Approved Application Stack
Generated backend services MUST use FastAPI, PydanticAI, Pydantic configuration models, and Scalar for API documentation.

## Principle 2: Standard Project Layout
Backend APIs live under backend/apis. Database artifacts live under database.${plan.includeFrontend ? ' Frontend code lives under frontend.' : ''}${functionsLayout}

## Principle 3: Infrastructure As Code
Cloud infrastructure MUST be defined with OpenTofu. Azure is the supported V1 provider.

## Principle 4: Local Development Parity
Projects MUST include Docker Compose for local development with PostgreSQL, Redis, local blob storage, and local messaging behavior.

## Principle 5: Observability And Operations
LLM workflows MUST include Langfuse tracing hooks and environment-specific configuration for ${plan.environments.map((environment) => environment.id).join(', ')}.
`;
}

export function renderSpecKitSpecTemplate(): string {
  return `# Feature Specification

## User Scenarios

## Requirements

## Success Criteria
`;
}

export function renderSpecKitPlanTemplate(): string {
  return `# Implementation Plan

## Technical Context

## Constitution Check

## Tasks
`;
}
