export { FileSystemError } from './domain/project/errors.js';
export { validateArtifactPathParts, manifestDisplayPath } from './domain/project/paths.js';
export { SUPPORTED_MANIFEST_VERSIONS, manifestHadFilteredLegacyNonDurableOwnership } from './domain/project/manifest/reader.js';
export { parseManifest, normalizeManifestProject, normalizeManifestFramework, loadManifest } from './application/project/manifest.js';
export { validateGeneratedProject } from './application/diagnose/generated-project.js';
export { resolveTargetRoot, findProjectRoot } from './adapters/filesystem/project-discovery.js';
export { artifactPath, resolveProjectPath } from './adapters/filesystem/project-paths.js';
export { assertNewOrEmptyDirectory, writeArtifacts, readProjectFile, writeProjectFile, deleteProjectFile } from './adapters/filesystem/project-files.js';
export { applyProjectFileTransaction, captureProjectFileSnapshot, ProjectFileTransactionError } from './adapters/filesystem/project-transaction.js';
export type { ProjectFileMutation, ProjectFileSnapshot } from './adapters/filesystem/project-transaction.js';
