import { codeAppsPlugin } from './catalogs.js';
import {
  powerAppsStarterCatalog,
  readPowerAppsStarterAsset,
  readPowerAppsStarterLicense
} from './power-apps-assets.js';
import type { AddArtifact } from './template-types.js';
import type { PowerAppsCodeAppProjectPlan } from './types.js';
import {
  OPEN_SPEC_DELIVERY,
  OPEN_SPEC_PROFILE,
  OPEN_SPEC_WORKFLOW_IDS
} from './openspec-profile.js';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function renderPackageJson(content: string, packageName: string): string {
  const parsed = JSON.parse(content) as unknown;
  if (!isRecord(parsed)) {
    throw new Error('Packaged Power Apps package.json must be an object.');
  }
  if (!isRecord(parsed.scripts)) {
    throw new Error('Packaged Power Apps package.json scripts must be an object.');
  }
  return JSON.stringify({
    ...parsed,
    name: packageName,
    scripts: {
      ...parsed.scripts,
      lint: 'eslint . --rule "react-refresh/only-export-components: off"'
    }
  }, null, 2);
}

function renderPackageLock(content: string, packageName: string): string {
  const parsed = JSON.parse(content) as unknown;
  if (!isRecord(parsed) || !isRecord(parsed.packages) || !isRecord(parsed.packages[''])) {
    throw new Error('Packaged Power Apps package-lock.json has an unsupported shape.');
  }
  return JSON.stringify({
    ...parsed,
    name: packageName,
    packages: {
      ...parsed.packages,
      '': {
        ...parsed.packages[''],
        name: packageName
      }
    }
  }, null, 2);
}

function renderReadme(plan: PowerAppsCodeAppProjectPlan): string {
  const agents = plan.agents
    .map((agent) => `${agent.label}${agent.id === plan.defaultAgent?.id ? ' (default)' : ''}`)
    .join(', ');
  const pluginGuidance = plan.codeAppsPlugin
    ? `
## Optional Code Apps agent plugin

This project requests the ${codeAppsPlugin.label}. In a selected agent session, add and install
only the targeted plugin:

\`\`\`text
/plugin marketplace add microsoft/power-platform-skills
/plugin install ${codeAppsPlugin.id}@${codeAppsPlugin.marketplace}
\`\`\`

Do not run \`/create-code-app\` here; Liftoff already created the application. Use the plugin's
connector and deployment skills for post-creation work.
`
    : '';
  const openSpecGuidance = plan.specWorkflow.id === 'openspec'
    ? [
        `- OpenSpec profile: ${OPEN_SPEC_PROFILE}; delivery: ${OPEN_SPEC_DELIVERY}; workflows: ${OPEN_SPEC_WORKFLOW_IDS.join(', ')}`,
        ...(plan.agents.some((agent) => agent.id === 'github-copilot')
          ? ['- GitHub Copilot cloud agent: controlled by `githubCopilot.cloudAgent` in `openspec/config.yaml`']
          : [])
      ].join('\n')
    : '';
  const governanceGuidance = plan.governanceProfile.id === 'none'
    ? 'Repository governance is disabled, so this project has no `/liftoff-setup` integration, managed phase graph, or credential-policy schema.'
    : 'When repository governance is enabled, `.liftoff/governance/README.md` explains deterministic setup. Run `/liftoff-setup` next from a selected agent; it completes, syncs, and archives the generated bootstrap seed, then stops at explicit authority gates. Rerun it to resume idempotently. Power Apps context does not invent a Liftoff backend, container, OpenTofu deployment, or API DAST lane.';
  return `# ${plan.projectName}

Power Apps code app generated by Mission Control Liftoff from Microsoft's official starter.

## Start locally

\`\`\`bash
npm ci
npm run dev
\`\`\`

## Bind to Power Apps

After dependencies are installed, initialize the local project with the packaged CLI:

\`\`\`bash
npx --no-install power-apps init
\`\`\`

Authentication, environment selection, connections, solutions, and deployment remain explicit
Microsoft Power Platform actions. Liftoff does not generate \`power.config.json\`, tenant data,
credentials, tokens, or connection identities.

## AI workflow

- Spec workflow: ${plan.specWorkflow.label} ${plan.framework.version}
- AI coding agents: ${agents}
${openSpecGuidance ? `${openSpecGuidance}\n` : ''}
- Microsoft Code Apps preview plugin: ${plan.codeAppsPlugin ? 'requested' : 'not requested'}

## Quality checks

The setup baseline is local only:

\`\`\`bash
npm run lint
npm run build
liftoff validate
liftoff doctor
\`\`\`

Backend tests, frontend subproject builds, Docker Compose validation, OpenTofu
format/init/validate, and API DAST are inapplicable because this generated
workload has no Liftoff backend, \`frontend/\`, \`docker-compose.yml\`, or
\`infrastructure/opentofu/azure\`. Setup does not run a live plan or apply, start
containers, deploy, mutate GitHub, or ask for cloud credentials. Commit/push and
Power Platform binding remain explicit; normal OpenSpec or Spec Kit feature and
release work follows after the seed is archived.

## Liftoff maintenance

\`liftoff upgrade --check\` and \`liftoff upgrade\` replace only a supported global Liftoff CLI installation. They do not modify this project. \`liftoff update --check\` and \`liftoff update\` maintain only explicit Liftoff core files.

The Power Apps starter, package metadata, lockfile, source, assets, and this README are project-owned after generation. No update mode, including \`--force\`, replaces them. Adopting a newer packaged starter is a separately reviewed project migration; the existing non-Liftoff \`migrate\` command does not perform an in-place upgrade.

For an existing OpenSpec project, change workflow delivery with \`openspec config profile\` and refresh framework-owned files with \`openspec update\`. Plain \`liftoff update\` does not regenerate OpenSpec integrations.

${governanceGuidance}
${pluginGuidance}
## Source

- Repository: ${plan.starter.repository}
- Template: \`${plan.starter.path}\`
- Commit: \`${plan.starter.commit}\`
- License: MIT; see \`THIRD_PARTY_NOTICES.md\`
`;
}

function renderAttribution(plan: PowerAppsCodeAppProjectPlan): string {
  return `# Third-party notices

## Microsoft PowerAppsCodeApps starter

This project includes files derived from:

- Repository: ${plan.starter.repository}
- Path: \`${plan.starter.path}\`
- Commit: \`${plan.starter.commit}\`
- License: MIT

Liftoff replaces the starter package name, supplies a deterministic generated lockfile, adjusts
the lint command for starter modules that intentionally export shared variants or context, and
replaces the starter README with workload and environment-binding guidance. Other starter files
are packaged byte-for-byte from the recorded commit.

${readPowerAppsStarterLicense().trimEnd()}
`;
}

export function addPowerAppsCodeAppArtifacts(
  add: AddArtifact,
  plan: PowerAppsCodeAppProjectPlan
): void {
  for (const asset of powerAppsStarterCatalog.files) {
    const source = readPowerAppsStarterAsset(asset);
    const content = asset.logicalName === 'power-apps-package'
      ? renderPackageJson(source, plan.packageName)
      : asset.logicalName === 'power-apps-lock'
        ? renderPackageLock(source, plan.packageName)
        : asset.logicalName === 'power-apps-readme'
          ? renderReadme(plan)
          : source;
    add(asset.logicalName, 'power-apps-starter', asset.pathParts, content);
  }
  add(
    'power-apps-attribution',
    'documentation',
    ['THIRD_PARTY_NOTICES.md'],
    renderAttribution(plan)
  );
}
